### PR TITLE
Install QT5 instead of QT4

### PR DESCRIPTION
**Pull request by rupurt**

### CODE REVIEW

**Comment by iwz** [comment]
Heyo!

Does this work as recommend here? https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012

**Comment by attack** [comment]
Hey Ian!  I am not on Sierra yet, so I can't check, but I will have @rupurt give it a shot.

Are you trying to confirm the instructions are correct?

**Comment by rupurt** [comment]
What's up @iwz!!

I've updated and confirmed that it now works on Sierra.

**Comment by iwz** [comment]
@attack yeah, this step seems much easier. if `brew` can be used, i'd love to update the instructions there

**Comment by attack** [comment]
@rupurt this change has been made, but in a refactored way.  Closing this PR.

**Pull request closed without merging**
